### PR TITLE
Feat wordld game

### PR DESCRIPTION
**Pull request by bestlyg**

### CODE REVIEW

**Comment by MedovTimur** [comment]
Hi!
Let's try to fix the tests, in your ci.yml file, you specify the following commands:
`cargo clippy --all-targets -- -D warnings -A unused-imports`
`cargo t`
but in the tests you specify the following path `"../target/wasm32-unknown-unknown/release/wordle_game.opt.wasm"`.
Change `release` to `debug`, or change the commands to
`cargo clippy --release --all-targets -- -D warnings -A unused-imports`
`cargo t -r`

**Comment by bestlyg** [comment]
> Hi! Let's try to fix the tests, in your ci.yml file, you specify the following commands: `cargo clippy --all-targets -- -D warnings -A unused-imports` `cargo t` but in the tests you specify the following path `"../target/wasm32-unknown-unknown/release/wordle_game.opt.wasm"`. Change `release` to `debug`, or change the commands to `cargo clippy --release --all-targets -- -D warnings -A unused-imports` `cargo t -r`

thanks for your help to fix the ci problem. it is works! i have fixed the ci.yml.

**Comment by MedovTimur** [comment]
Hi!
why do you need `wait`/`wake` functions in your code? 
and in case I send `WordleAction::CheckWord`, I can't get a reply with the result of my move, can I?

**Comment by bestlyg** [comment]
> Hi! why do you need `wait`/`wake` functions in your code? and in case I send `WordleAction::CheckWord`, I can't get a reply with the result of my move, can I?

I use the `wait` / `wake` functions owing to that [the assignment of Intermediate Course](https://academy.gear.foundation/courses/take/intermediate-course/multimedia/54008662-assignment) must use this funcion to finish.
image

**Comment by bestlyg** [comment]
> Hi! why do you need `wait`/`wake` functions in your code? and in case I send `WordleAction::CheckWord`, I can't get a reply with the result of my move, can I?

I think we don't need to consider the issue that the another contract can't reply, because the standard contract of  Wordle Program is given in the assignment.

**Comment by MedovTimur** [comment]
> > Hi! why do you need `wait`/`wake` functions in your code? and in case I send `WordleAction::CheckWord`, I can't get a reply with the result of my move, can I?
> 
> I use the `wait` / `wake` functions owing to that [the assignment of Intermediate Course](https://academy.gear.foundation/courses/take/intermediate-course/multimedia/54008662-assignment) must use this funcion to finish. image

Well, in your code wait and wake have no functionality, right?

**Comment by MedovTimur** [comment]
> `WordleAction::CheckWord`



> > Hi! why do you need `wait`/`wake` functions in your code? and in case I send `WordleAction::CheckWord`, I can't get a reply with the result of my move, can I?
> 
> I think we don't need to consider the issue that the another contract can't reply, because the standard contract of Wordle Program is given in the assignment.

and what reply will the player get when he sends `WordleAction::CheckWord`?
Will this reply be informative so that he understands what is going on and what result he got?

**Comment by bestlyg** [comment]
> > `WordleAction::CheckWord`
> 
> > > Hi! why do you need `wait`/`wake` functions in your code? and in case I send `WordleAction::CheckWord`, I can't get a reply with the result of my move, can I?
> > 
> > 
> > I think we don't need to consider the issue that the another contract can't reply, because the standard contract of Wordle Program is given in the assignment.
> 
> and what reply will the player get when he sends `WordleAction::CheckWord`? Will this reply be informative so that he understands what is going on and what result he got?

sry, i think it works in my code. Could tell me where the code will run wrong?

the process:

If user send `WordleAction::CheckWord` when the status is `WordleStatus::GameStarted`, it will trigger `wait()`, send msg to wordle program and update status to `WordleStatus::CheckWordMessageSent`.

image

when the wordle program reply the contract, it will trigger `wake()` to run `handle` function and the status will be set to `WordleStatus::GameOver` or `WordleStatus::CheckWordMessageReceived`.

image

if now the status is `WordleStatus::GameOver`, handle will reply a event.

image


if now the status is `WordleStatus::CheckWordMessageReceived`, handle will reply another event.

image

If user send `WordleAction::CheckWord` when the status is `WordleStatus::Init` , `WordleStatus::GameStartMessageSent`, `WordleStatus::CheckWordMessageSent` , the contract will reply `WordleEvent::WrongActionToTrigger`.

image

**Comment by MedovTimur** [comment]
Great job, I can see now that the code is working properly and you have a good understanding of the material, thanks for completing the course

**Comment by bestlyg** [comment]
> Great job, I can see now that the code is working properly and you have a good understanding of the material, thanks for completing the course

Thanks for your reply and checking!

**Pull request merged**
